<div>
    <x-ui.card class="p-8 w-full">
        <div class="space-y-6" x-data="{
            search: '',
            selected: [],
            get allIds() { return {{ $packages->pluck('id')->toJson() }}; },
            get allSelected() { return this.selected.length === this.allIds.length && this.allIds.length > 0; },
            toggleAll() {
                if (this.allSelected) {
                    this.selected = [];
                } else {
                    this.selected = [...this.allIds];
                }
            },
            toggleOne(id) {
                const idx = this.selected.indexOf(id);
                if (idx === -1) {
                    this.selected.push(id);
                } else {
                    this.selected.splice(idx, 1);
                }
            },
            clearSelection() {
                this.selected = [];
            },
            matches(env, project, version, package_name) {
                if (!this.search) return true;
                const q = this.search.toLowerCase();
                return env.toLowerCase().includes(q) ||
                       project.toLowerCase().includes(q) ||
                       version.toLowerCase().includes(q) ||
                       package_name.toLowerCase().includes(q);
            },
            async bulkDownload(format) {
                const form = document.createElement('form');
                form.method = 'POST';
                form.action = '{{ route('deployments.bulk-download') }}';
                const token = document.createElement('input');
                token.type = 'hidden'; token.name = '_token'; token.value = '{{ csrf_token() }}';
                const fmtInput = document.createElement('input');
                fmtInput.type = 'hidden'; fmtInput.name = 'format'; fmtInput.value = format;
                form.appendChild(token);
                form.appendChild(fmtInput);
                this.selected.forEach(id => {
                    const el = document.createElement('input');
                    el.type = 'hidden'; el.name = 'ids[]'; el.value = id;
                    form.appendChild(el);
                });
                document.body.appendChild(form);
                form.submit();
                document.body.removeChild(form);
            },
            async bulkDelete() {
                if (!confirm(this.selected.length + ' package(s) will be permanently deleted. Continue?')) return;
                const resp = await fetch('{{ route('deployments.bulk-delete') }}', {
                    method: 'DELETE',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    },
                    body: JSON.stringify({ ids: this.selected })
                });
                if (resp.ok) {
                    window.location.reload();
                } else {
                    alert('Delete failed. Please try again.');
                }
            }
        }">
            <div class="flex flex-col md:flex-row md:items-center justify-between ">
                <div>
                    <h2 class="text-xl font-semibold text-slate-900">Previously Generated Packages</h2>
                    <p class="text-sm text-slate-500 mt-1">
                        View and download packages that was previously generated by you.
                    </p>
                    <div class="relative w-full md:w-64 mt-6">
                        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                            <svg class="w-4 h-4 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                            </svg>
                        </div>
                        <input type="text" x-model="search"
                            class="block w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-4 py-2 text-sm text-slate-700 focus:border-blue-500 focus:ring-blue-500 transition-all outline-none"
                            placeholder="Search packages...">
                    </div>
                </div>
            </div>

            @if($packages->isEmpty())
                <div class="rounded-lg border border-slate-200 bg-white p-6 text-slate-600">
                    No completed packages found.
                </div>
            @else
                <div class="relative rounded-xl border border-slate-200 bg-white overflow-hidden">
                    <div {{-- class="max-h-[520px] overflow-y-auto custom-scrollbar" --}}>
                        <table class="min-w-full divide-y divide-slate-200 w-full table-auto">
                            <thead class="bg-slate-50 sticky top-0 z-20">
                                <tr>
                                    <th class="px-4 py-3 w-10">
                                        <input type="checkbox"
                                            class="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500 cursor-pointer"
                                            :checked="allSelected"
                                            @click.prevent="toggleAll()">
                                    </th>
                                    <th class="px-4 py-3 text-left text-sm font-semibold text-slate-700">Env</th>
                                    <th class="px-4 py-3 text-left text-sm font-semibold text-slate-700">Project</th>
                                    <th class="px-4 py-3 text-left text-sm font-semibold text-slate-700">Version</th>
                                    <th class="px-4 py-3 text-left text-sm font-semibold text-slate-700">Created</th>
                                    <th class="px-4 py-3"></th>
                                    <th class="px-4 py-3"></th>
                                    <th class="px-4 py-3"></th>
                                </tr>
                            </thead>
                            @foreach($packages as $package)
                                <tbody x-data="{ expanded: false }"
                                    x-show="matches('{{ $package->environment }}', '{{ $package->project_name }}', '{{ $package->base_version }} {{ $package->head_version }}', '{{ $package->package_name }}')"
                                    class="divide-y divide-slate-100">
                                    <tr @click="expanded = !expanded" class="cursor-pointer hover:bg-slate-50 transition-colors"
                                        :class="selected.includes({{ $package->id }}) ? 'bg-blue-50/60' : ''">
                                        <td class="px-4 py-3 w-10" @click.stop>
                                            <input type="checkbox"
                                                class="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500 cursor-pointer"
                                                :checked="selected.includes({{ $package->id }})"
                                                @change="toggleOne({{ $package->id }})">
                                        </td>
                                        <td class="px-4 py-3 text-sm text-slate-800">{{ $package->environment }}</td>
                                        <td class="px-4 py-3 text-sm font-bold text-slate-800">{{ $package->project_name }}</td>
                                        <td class="px-4 py-3 text-sm text-slate-800">
                                            <div class="flex items-center gap-2">
                                                <span
                                                    class="px-2 py-0.5 rounded border border-rose-100 bg-rose-50 text-rose-700 font-medium text-sm whitespace-nowrap">{{ $package->base_version }}</span>
                                                <span class="text-slate-700 text-lg">→</span>
                                                <span
                                                    class="px-2 py-0.5 rounded border border-emerald-100 bg-emerald-50 text-emerald-700 font-medium text-sm whitespace-nowrap">{{ $package->head_version }}</span>
                                            </div>
                                        </td>
                                        <td class="px-4 py-3 text-sm text-slate-700 whitespace-nowrap">
                                            {{ $package->created_at->format('d M Y, h:i A') }}
                                        </td>
                                        <td class="px-4 py-3" @click.stop>
                                            <div class="flex items-center gap-2">
                                                <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16"
                                                    class="shrink-0 text-slate-500">
                                                    <path fill="currentColor"
                                                        d="M3.5 1.75v11.5c0 .09.048.173.126.217a.75.75 0 0 1-.752 1.298A1.748 1.748 0 0 1 2 13.25V1.75C2 .784 2.784 0 3.75 0h5.586c.464 0 .909.185 1.237.513l2.914 2.914c.329.328.513.773.513 1.237v8.586A1.75 1.75 0 0 1 12.25 15h-.5a.75.75 0 0 1 0-1.5h.5a.25.25 0 0 0 .25-.25V4.664a.25.25 0 0 0-.073-.177L9.513 1.573a.25.25 0 0 0-.177-.073H7.25a.75.75 0 0 1 0 1.5h-.5a.75.75 0 0 1 0-1.5h-3a.25.25 0 0 0-.25.25Zm3.75 8.75h.5c.966 0 1.75.784 1.75 1.75v3a.75.75 0 0 1-.75.75h-2.5a.75.75 0 0 1-.75-.75v-3c0-.966.784-1.75 1.75-1.75ZM6 5.25a.75.75 0 0 1 .75-.75h.5a.75.75 0 0 1 0 1.5h-.5A.75.75 0 0 1 6 5.25Zm.75 2.25h.5a.75.75 0 0 1 0 1.5h-.5a.75.75 0 0 1 0-1.5ZM8 6.75A.75.75 0 0 1 8.75 6h.5a.75.75 0 0 1 0 1.5h-.5A.75.75 0 0 1 8 6.75ZM8.75 3h.5a.75.75 0 0 1 0 1.5h-.5a.75.75 0 0 1 0-1.5ZM8 9.75A.75.75 0 0 1 8.75 9h.5a.75.75 0 0 1 0 1.5h-.5A.75.75 0 0 1 8 9.75Zm-1 2.5v2.25h1v-2.25a.25.25 0 0 0-.25-.25h-.5a.25.25 0 0 0-.25.25Z">
                                                    </path>
                                                </svg>
                                                <a href="{{ route('download.archive', ['folder' => $package->package_name, 'format' => '.zip']) }}"
                                                    class="flex items-center gap-1.5 group">
                                                    <span class="text-blue-600 group-hover:underline">
                                                        <svg class="h-5 w-5" viewBox="0 0 15 15" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M7.50005 1.04999C7.74858 1.04999 7.95005 1.25146 7.95005 1.49999V8.41359L10.1819 6.18179C10.3576 6.00605 10.6425 6.00605 10.8182 6.18179C10.994 6.35753 10.994 6.64245 10.8182 6.81819L7.81825 9.81819C7.64251 9.99392 7.35759 9.99392 7.18185 9.81819L4.18185 6.81819C4.00611 6.64245 4.00611 6.35753 4.18185 6.18179C4.35759 6.00605 4.64251 6.00605 4.81825 6.18179L7.05005 8.41359V1.49999C7.05005 1.25146 7.25152 1.04999 7.50005 1.04999ZM2.5 10C2.77614 10 3 10.2239 3 10.5V12C3 12.5539 3.44565 13 3.99635 13H11.0012C11.5529 13 12 12.5528 12 12V10.5C12 10.2239 12.2239 10 12.5 10C12.7761 10 13 10.2239 13 10.5V12C13 13.1041 12.1062 14 11.0012 14H3.99635C2.89019 14 2 13.103 2 12V10.5C2 10.2239 2.22386 10 2.5 10Z"/>
                                                        </svg>
                                                    </span>
                                                    <span class="text-sm text-blue-600 font-medium group-hover:underline">
                                                        Package
                                                    </span>
                                                    <span class="text-sm text-blue-600 font-bold group-hover:underline">
                                                        (.zip)
                                                    </span>
                                                </a>
                                            </div>
                                        </td>
                                        <td class="px-4 py-3" @click.stop>
                                            <div class="flex items-center gap-2">
                                                <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16"
                                                    class="shrink-0 text-slate-500">
                                                    <path fill="currentColor"
                                                        d="M3.5 1.75v11.5c0 .09.048.173.126.217a.75.75 0 0 1-.752 1.298A1.748 1.748 0 0 1 2 13.25V1.75C2 .784 2.784 0 3.75 0h5.586c.464 0 .909.185 1.237.513l2.914 2.914c.329.328.513.773.513 1.237v8.586A1.75 1.75 0 0 1 12.25 15h-.5a.75.75 0 0 1 0-1.5h.5a.25.25 0 0 0 .25-.25V4.664a.25.25 0 0 0-.073-.177L9.513 1.573a.25.25 0 0 0-.177-.073H7.25a.75.75 0 0 1 0 1.5h-.5a.75.75 0 0 1 0-1.5h-3a.25.25 0 0 0-.25.25Zm3.75 8.75h.5c.966 0 1.75.784 1.75 1.75v3a.75.75 0 0 1-.75.75h-2.5a.75.75 0 0 1-.75-.75v-3c0-.966.784-1.75 1.75-1.75ZM6 5.25a.75.75 0 0 1 .75-.75h.5a.75.75 0 0 1 0 1.5h-.5A.75.75 0 0 1 6 5.25Zm.75 2.25h.5a.75.75 0 0 1 0 1.5h-.5a.75.75 0 0 1 0-1.5ZM8 6.75A.75.75 0 0 1 8.75 6h.5a.75.75 0 0 1 0 1.5h-.5A.75.75 0 0 1 8 6.75ZM8.75 3h.5a.75.75 0 0 1 0 1.5h-.5a.75.75 0 0 1 0-1.5ZM8 9.75A.75.75 0 0 1 8.75 9h.5a.75.75 0 0 1 0 1.5h-.5A.75.75 0 0 1 8 9.75Zm-1 2.5v2.25h1v-2.25a.25.25 0 0 0-.25-.25h-.5a.25.25 0 0 0-.25.25Z">
                                                    </path>
                                                </svg>
                                                <a href="{{ route('download.archive', ['folder' => $package->package_name, 'format' => '.tar.gz']) }}"
                                                    class="flex items-center gap-1.5 group">
                                                    <span class="text-blue-600 group-hover:underline">
                                                        <svg class="h-5 w-5" viewBox="0 0 15 15" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M7.50005 1.04999C7.74858 1.04999 7.95005 1.25146 7.95005 1.49999V8.41359L10.1819 6.18179C10.3576 6.00605 10.6425 6.00605 10.8182 6.18179C10.994 6.35753 10.994 6.64245 10.8182 6.81819L7.81825 9.81819C7.64251 9.99392 7.35759 9.99392 7.18185 9.81819L4.18185 6.81819C4.00611 6.64245 4.00611 6.35753 4.18185 6.18179C4.35759 6.00605 4.64251 6.00605 4.81825 6.18179L7.05005 8.41359V1.49999C7.05005 1.25146 7.25152 1.04999 7.50005 1.04999ZM2.5 10C2.77614 10 3 10.2239 3 10.5V12C3 12.5539 3.44565 13 3.99635 13H11.0012C11.5529 13 12 12.5528 12 12V10.5C12 10.2239 12.2239 10 12.5 10C12.7761 10 13 10.2239 13 10.5V12C13 13.1041 12.1062 14 11.0012 14H3.99635C2.89019 14 2 13.103 2 12V10.5C2 10.2239 2.22386 10 2.5 10Z"/>
                                                        </svg>
                                                    </span>
                                                    <span class="text-sm text-blue-600 font-medium group-hover:underline">
                                                        Package
                                                    </span>
                                                    <span class="text-sm text-blue-600 font-bold group-hover:underline">
                                                        (.tar.gz)
                                                    </span>
                                                </a>
                                            </div>
                                        </td>
                                        <td class="px-4 py-3 text-right">
                                            <svg xmlns="http://www.w3.org/2000/svg"
                                                class="h-5 w-5 inline-block shrink-0 text-slate-400 transition-transform duration-200"
                                                :class="expanded ? '' : 'rotate-90'" fill="none" viewBox="0 0 24 24"
                                                stroke="currentColor" stroke-width="2">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" />
                                            </svg>
                                        </td>
                                    </tr>
                                    <tr x-show="expanded" x-cloak class="bg-slate-50 border-t border-slate-100">
                                        <td colspan="8" class="px-6 py-5">
                                            <div class="flex flex-col space-y-5 max-w-4xl">
                                                <!-- Package Name & Meta -->
                                                <div>
                                                    <div class="text-base text-slate-800">
                                                        <span class="font-bold">Package:</span> <span
                                                            class="font-bold">{{ $package->package_name }}</span>
                                                    </div>
                                                    <div class="text-xs text-slate-500 mt-1 flex items-center space-x-2">
                                                        <span>zip :</span>
                                                        <span>Size: {{ $package->zip_size ?? 'N/A' }}</span>
                                                        <span class="text-slate-300">|</span>
                                                        <span>SHA256:
                                                            {{ $package->zip_sha256 ?? 'N/A' }}</span>
                                                    </div>
                                                    <div class="text-xs text-slate-500 mt-1 flex items-center space-x-2">
                                                        <span>tar.gz :</span>
                                                        <span>Size: {{ $package->targz_size ?? 'N/A' }}</span>
                                                        <span class="text-slate-300">|</span>
                                                        <span>SHA256:
                                                            {{ $package->targz_sha256 ?? 'N/A' }}</span>
                                                    </div>
                                                </div>

                                                <!-- Deploy to Hosting Server -->
                                                <div>
                                                    <h4 class="text-base font-bold text-slate-800 mb-3">Deploy to Hosting
                                                        Server</h4>
                                                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                        <!-- Server Type -->
                                                        <div>
                                                            <label class="block text-sm font-semibold text-slate-700 mb-2">Server
                                                                Type</label>
                                                            <select
                                                                class="block w-full rounded-md border border-slate-300 py-2 px-3 text-sm focus:border-blue-500 focus:ring focus:ring-blue-200 bg-white">
                                                                <option value="">Select a server profile...</option>
                                                            </select>
                                                        </div>
                                                        <!-- Deployment Path -->
                                                        <div>
                                                            <label
                                                                class="block text-sm font-semibold text-slate-700 mb-2">Deployment
                                                                Path</label>
                                                            <input type="text"
                                                                class="block w-full rounded-md border border-slate-300 py-2 px-3 text-sm focus:border-blue-500 focus:ring focus:ring-blue-200 bg-white"
                                                                value="">
                                                        </div>
                                                    </div>

                                                    <!-- Deploy Button -->
                                                    <div class="mt-5 flex justify-center">
                                                        <button type="button"
                                                            class="inline-flex items-center justify-center gap-3 rounded-2xl bg-blue-600 px-6 py-4 text-base font-medium text-white shadow-sm transition hover:bg-blue-700">
                                                            <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                                                                stroke="currentColor" stroke-width="1.8">
                                                                <path stroke-linecap="round" stroke-linejoin="round"
                                                                    d="M4 17h16M7 17V7h10v10M9 7V5h6v2" />
                                                            </svg>
                                                            <span>Deploy Now</span>
                                                            <span
                                                                class="rounded-lg bg-blue-100 px-2.5 py-1 text-xs font-semibold text-blue-700">Ready</span>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            @endforeach
                        </table>
                    </div>

                    <!-- Floating Bulk Action Bar -->
                    <div x-show="selected.length > 0" x-cloak x-transition:enter="transition ease-out duration-200"
                        x-transition:enter-start="opacity-0 translate-y-2" x-transition:enter-end="opacity-100 translate-y-0"
                        x-transition:leave="transition ease-in duration-150"
                        x-transition:leave-start="opacity-100 translate-y-0" x-transition:leave-end="opacity-0 translate-y-2"
                        class="absolute bottom-4 left-1/2 -translate-x-1/2 z-30">
                        <div class="flex items-center gap-1 rounded-xl border border-slate-200 bg-white shadow-xl px-3 py-2 text-sm whitespace-nowrap">
                            <!-- Count -->
                            <span class="font-semibold text-slate-700 pr-2 border-r border-slate-200 mr-1">
                                <span x-text="selected.length"></span> Selected
                            </span>

                            <!-- Download ZIP -->
                            <button @click="bulkDownload('.zip')"
                                class="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-blue-600 hover:bg-slate-100 transition font-medium hover:underline">
                                <svg class="h-5 w-5" viewBox="0 0 15 15" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M7.50005 1.04999C7.74858 1.04999 7.95005 1.25146 7.95005 1.49999V8.41359L10.1819 6.18179C10.3576 6.00605 10.6425 6.00605 10.8182 6.18179C10.994 6.35753 10.994 6.64245 10.8182 6.81819L7.81825 9.81819C7.64251 9.99392 7.35759 9.99392 7.18185 9.81819L4.18185 6.81819C4.00611 6.64245 4.00611 6.35753 4.18185 6.18179C4.35759 6.00605 4.64251 6.00605 4.81825 6.18179L7.05005 8.41359V1.49999C7.05005 1.25146 7.25152 1.04999 7.50005 1.04999ZM2.5 10C2.77614 10 3 10.2239 3 10.5V12C3 12.5539 3.44565 13 3.99635 13H11.0012C11.5529 13 12 12.5528 12 12V10.5C12 10.2239 12.2239 10 12.5 10C12.7761 10 13 10.2239 13 10.5V12C13 13.1041 12.1062 14 11.0012 14H3.99635C2.89019 14 2 13.103 2 12V10.5C2 10.2239 2.22386 10 2.5 10Z"/>
                                </svg>
                                <span class="font-medium ">
                                    Download
                                </span>
                                <span class="font-bold ">
                                    .zip
                                </span>
                            </button>

                            <!-- Divider -->
                            <span class="text-slate-200">|</span>

                            <!-- Download TAR.GZ -->
                            <button @click="bulkDownload('.tar.gz')"
                                class="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-blue-600 hover:bg-slate-100 transition font-medium hover:underline">
                                <svg class="h-5 w-5" viewBox="0 0 15 15" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M7.50005 1.04999C7.74858 1.04999 7.95005 1.25146 7.95005 1.49999V8.41359L10.1819 6.18179C10.3576 6.00605 10.6425 6.00605 10.8182 6.18179C10.994 6.35753 10.994 6.64245 10.8182 6.81819L7.81825 9.81819C7.64251 9.99392 7.35759 9.99392 7.18185 9.81819L4.18185 6.81819C4.00611 6.64245 4.00611 6.35753 4.18185 6.18179C4.35759 6.00605 4.64251 6.00605 4.81825 6.18179L7.05005 8.41359V1.49999C7.05005 1.25146 7.25152 1.04999 7.50005 1.04999ZM2.5 10C2.77614 10 3 10.2239 3 10.5V12C3 12.5539 3.44565 13 3.99635 13H11.0012C11.5529 13 12 12.5528 12 12V10.5C12 10.2239 12.2239 10 12.5 10C12.7761 10 13 10.2239 13 10.5V12C13 13.1041 12.1062 14 11.0012 14H3.99635C2.89019 14 2 13.103 2 12V10.5C2 10.2239 2.22386 10 2.5 10Z"/>
                                </svg>
                                <span class="font-medium ">
                                    Download
                                </span>
                                <span class="font-bold ">
                                    .tar.gz
                                </span>
                            </button>

                            <!-- Divider -->
                            <span class="text-slate-200">|</span>

                            <!-- Delete -->
                            <button @click="bulkDelete()"
                                class="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-red-600 hover:bg-red-50 transition font-medium">
                                <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/>
                                </svg>
                                Delete
                            </button>

                            <!-- Divider -->
                            <span class="text-slate-200">|</span>

                            <!-- Close / Deselect all -->
                            <button @click="clearSelection()"
                                class="flex items-center justify-center h-7 w-7 rounded-lg text-slate-400 hover:bg-slate-100 hover:text-slate-600 transition">
                                <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/>
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </x-ui.card>
</div>